# ОНПД. Лабораторна робота №3

In [2]:
# Завантажуємо початкові модулі
import pandas as pd
import numpy as np

# Читаємо весь набір даних
athletics = pd.read_csv("archive/results/Athletics.csv")

# Встановлюємо зерно для генератора випадкових чисел
np.random.seed(42)

###  Перше ознайомлення з даними

In [4]:
# Переглянемо перші 5 рядків датасету. Бачимо пропущені дані
athletics.head(5)

,date,stage_code,event_code,event_name,event_stage,stage,gender,discipline_name,discipline_code,venue,...,participant_country_code,participant_country,rank,result,result_type,result_IRM,result_diff,qualification_mark,start_order,bib
0,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,GBR,Great Britain,1.0,3:10.61,TIME,NaN,NaN,Q,4.0,NaN
1,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,NED,Netherlands,2.0,3:10.81,TIME,NaN,NaN,Q,6.0,NaN
2,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,ITA,Italy,3.0,3:11.59,TIME,NaN,NaN,Q,3.0,NaN
3,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,NGR,Nigeria,4.0,3:11.99,TIME,NaN,NaN,NaN,5.0,NaN
4,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,IRL,Ireland,5.0,3:12.67,TIME,NaN,NaN,NaN,7.0,NaN

### Визначення кількості відсутніх даних

In [6]:
# Отримуємо кількість відсутніх елементів даних по стовпцях
missing_values_count = athletics.isnull().sum()

# Виводимо кількість відсутніх елементів у стовпцях
missing_values_count

date                           0
stage_code                     0
event_code                     0
event_name                     0
event_stage                    0
stage                          0
gender                         0
discipline_name                0
discipline_code                0
venue                         45
participant_code               0
participant_name               0
participant_type               0
participant_country_code       0
participant_country            0
rank                         141
result                       141
result_type                    0
result_IRM                  3198
result_diff                 3042
qualification_mark          2323
start_order                   45
bib                          146
dtype: int64

In [7]:
# Визначаємо загальну кількість відсутніх елементів даних
total_cells = np.product(athletics.shape)
total_missing = missing_values_count.sum()

# Визначаємо відсоток відсутніх елементів даних
percent_missing = (total_missing / total_cells) * 100
percent_missing

11.824680651587952

### Визначення причини відсутності даних

In [9]:
# Усі інші стовпці, крім venue, мають пропущені дані за визначенням (їх просто не існує)
missing_values_count.loc['venue']

45

### Видалення відсутніх елементів даних

In [11]:
# Видаляємо всі рядки, що містять відсутні значення
athletics.dropna()

Empty DataFrame
Columns: [date, stage_code, event_code, event_name, event_stage, stage, gender, discipline_name, discipline_code, venue, participant_code, participant_name, participant_type, participant_country_code, participant_country, rank, result, result_type, result_IRM, result_diff, qualification_mark, start_order, bib]
Index: []

[0 rows x 23 columns]

In [12]:
# Видаляємо всі стовпці, що містять відсутні значення
columns_with_na_dropped = athletics.dropna(axis=1)
columns_with_na_dropped.head()

,date,stage_code,event_code,event_name,event_stage,stage,gender,discipline_name,discipline_code,participant_code,participant_name,participant_type,participant_country_code,participant_country,result_type
0,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,ATHX4X400M--GBR01,Great Britain,Team,GBR,Great Britain,TIME
1,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,ATHX4X400M--NED01,Netherlands,Team,NED,Netherlands,TIME
2,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,ATHX4X400M--ITA01,Italy,Team,ITA,Italy,TIME
3,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,ATHX4X400M--NGR01,Nigeria,Team,NGR,Nigeria,TIME
4,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,ATHX4X400M--IRL01,Ireland,Team,IRL,Ireland,TIME

In [13]:
# Визначимо кількість втрачених даних
print("Кількість стовпців : %d \n" % athletics.shape[1])
print("Кількість видалених стовпців: %d" % columns_with_na_dropped.shape[1])

Кількість стовпців : 23

Кількість видалених стовпців: 15

In [14]:
# Заповнення відсутніх елементів даних нулями
athletics.fillna(0)

,date,stage_code,event_code,event_name,event_stage,stage,gender,discipline_name,discipline_code,venue,...,participant_country_code,participant_country,rank,result,result_type,result_IRM,result_diff,qualification_mark,start_order,bib
0,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,GBR,Great Britain,1.0,3:10.61,TIME,0,0,Q,4.0,0.0
1,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,NED,Netherlands,2.0,3:10.81,TIME,0,0,Q,6.0,0.0
2,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,ITA,Italy,3.0,3:11.59,TIME,0,0,Q,3.0,0.0
3,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,NGR,Nigeria,4.0,3:11.99,TIME,0,0,0,5.0,0.0
4,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,IRL,Ireland,5.0,3:12.67,TIME,0,0,0,7.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3334,2024-08-03T21:47:12+02:00,ATHWTRPLJUMP----------FNL-000100--,ATHWTRPLJUMP,Women's Triple Jump,Women's Triple Jump Final,Final,W,Athletics,ATH,Stade de France,...,ITA,Italy,8.0,14.14,DISTANCE,0,0,0,10.0,2017.0
3335,2024-08-03T21:47:12+02:00,ATHWTRPLJUMP----------FNL-000100--,ATHWTRPLJUMP,Women's Triple Jump,Women's Triple Jump Final,Final,W,Athletics,ATH,Stade de France,...,USA,United States,9.0,14.05,DISTANCE,0,0,0,8.0,2462.0
3336,2024-08-03T21:47:12+02:00,ATHWTRPLJUMP----------FNL-000100--,ATHWTRPLJUMP,Women's Triple Jump,Women's Triple Jump Final,Final,W,Athletics,ATH,Stade de France,...,ROU,Romania,10.0,14.03,DISTANCE,0,0,0,6.0,2303.0
3337,2024-08-03T21:47:12+02:00,ATHWTRPLJUMP----------FNL-000100--,ATHWTRPLJUMP,Women's Triple Jump,Women's Triple Jump Final,Final,W,Athletics,ATH,Stade de France,...,UKR,Ukraine,11.0,13.98,DISTANCE,0,0,0,9.0,2401.0
3338,2024-08-03T21:47:12+02:00,ATHWTRPLJUMP----------FNL-000100--,ATHWTRPLJUMP,Women's Triple Jump,Women's Triple Jump Final,Final,W,Athletics,ATH,Stade de France,...,FRA,France,12.0,13.78,DISTANCE,0,0,0,7.0,1830.0

In [15]:
# Створення піднабору даних
subset_athletics = athletics.loc[athletics.venue.isnull()][['event_name', 'venue']]
subset_athletics.head()

           event_name venue
1273  Men's Decathlon   NaN
1274  Men's Decathlon   NaN
1275  Men's Decathlon   NaN
1276  Men's Decathlon   NaN
1277  Men's Decathlon   NaN

In [16]:
# Заповнення стовпця venue правильним значенням
subset_athletics.fillna('Stade de France').head()

           event_name            venue
1273  Men's Decathlon  Stade de France
1274  Men's Decathlon  Stade de France
1275  Men's Decathlon  Stade de France
1276  Men's Decathlon  Stade de France
1277  Men's Decathlon  Stade de France

In [17]:
# Заповнення наступним по черзі значенням
athletics.fillna(method='bfill', axis=0).fillna(0)

C:\Users\IVAN\AppData\Local\Temp\ipykernel_19224\3420732014.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  athletics.fillna(method='bfill', axis=0).fillna(0)

,date,stage_code,event_code,event_name,event_stage,stage,gender,discipline_name,discipline_code,venue,...,participant_country_code,participant_country,rank,result,result_type,result_IRM,result_diff,qualification_mark,start_order,bib
0,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,GBR,Great Britain,1.0,3:10.61,TIME,DQ,+0:51,Q,4.0,223.0
1,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,NED,Netherlands,2.0,3:10.81,TIME,DQ,+0:51,Q,6.0,223.0
2,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,ITA,Italy,3.0,3:11.59,TIME,DQ,+0:51,Q,3.0,223.0
3,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,NGR,Nigeria,4.0,3:11.99,TIME,DQ,+0:51,Q,5.0,223.0
4,2024-08-03T17:48:06+02:00,ATHX4X400M------------RND1000200--,ATHX4X400M,4 x 400m Relay Mixed,4 x 400m Relay Mixed Round 1 - Heat 2,Round 1 - Heat 2,X,Athletics,ATH,Stade de France,...,IRL,Ireland,5.0,3:12.67,TIME,DQ,+0:51,Q,7.0,223.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3334,2024-08-03T21:47:12+02:00,ATHWTRPLJUMP----------FNL-000100--,ATHWTRPLJUMP,Women's Triple Jump,Women's Triple Jump Final,Final,W,Athletics,ATH,Stade de France,...,ITA,Italy,8.0,14.14,DISTANCE,0,0,0,10.0,2017.0
3335,2024-08-03T21:47:12+02:00,ATHWTRPLJUMP----------FNL-000100--,ATHWTRPLJUMP,Women's Triple Jump,Women's Triple Jump Final,Final,W,Athletics,ATH,Stade de France,...,USA,United States,9.0,14.05,DISTANCE,0,0,0,8.0,2462.0
3336,2024-08-03T21:47:12+02:00,ATHWTRPLJUMP----------FNL-000100--,ATHWTRPLJUMP,Women's Triple Jump,Women's Triple Jump Final,Final,W,Athletics,ATH,Stade de France,...,ROU,Romania,10.0,14.03,DISTANCE,0,0,0,6.0,2303.0
3337,2024-08-03T21:47:12+02:00,ATHWTRPLJUMP----------FNL-000100--,ATHWTRPLJUMP,Women's Triple Jump,Women's Triple Jump Final,Final,W,Athletics,ATH,Stade de France,...,UKR,Ukraine,11.0,13.98,DISTANCE,0,0,0,9.0,2401.0
3338,2024-08-03T21:47:12+02:00,ATHWTRPLJUMP----------FNL-000100--,ATHWTRPLJUMP,Women's Triple Jump,Women's Triple Jump Final,Final,W,Athletics,ATH,Stade de France,...,FRA,France,12.0,13.78,DISTANCE,0,0,0,7.0,1830.0